import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ReactQueryClientWrapper } from '@/components/ReactQueryClientWrapper';
import { NextClientCookieWrapper } from '@/components/NextClientCookieWrapper';
import { ReduxStoreProvider } from '@/components/ReduxStoreProvider';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ReactQueryClientWrapper>
			<NextClientCookieWrapper>
				<ReduxStoreProvider>
					<html lang="en" className="h-screen">
						<body
							className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased`}
						>
							{children}
						</body>
					</html>
				</ReduxStoreProvider>
			</NextClientCookieWrapper>
		</ReactQueryClientWrapper>
	);
}
