spring:
  application:
    name: desaAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/desa
    username: postgres
    password: 31702005
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

